export enum RestaurantType {
    DESSERT = 'dessert',
    AMERICAN_RESTAURANT = 'american_restaurant',
    BAKERY = 'bakery',
    BAR = 'bar',
    BARBECUE_RESTAURANT = 'barbecue_restaurant',
    BRAZILIAN_RESTAURANT = 'brazilian_restaurant',
    BREAKFAST_RESTAURANT = 'breakfast_restaurant',
    BRUNCH_RESTAURANT = 'brunch_restaurant',
    CAFE = 'cafe',
    CHINESE_RESTAURANT = 'chinese_restaurant',
    COFFEE_SHOP = 'coffee_shop',
    FAST_FOOD_RESTAURANT = 'fast_food_restaurant',
    FRENCH_RESTAURANT = 'french_restaurant',
    GREEK_RESTAURANT = 'greek_restaurant',
    HAMBURGER_RESTAURANT = 'hamburger_restaurant',
    ICE_CREAM_SHOP = 'ice_cream_shop',
    INDIAN_RESTAURANT = 'indian_restaurant',
    INDONESIAN_RESTAURANT = 'indonesian_restaurant',
    ITALIAN_RESTAURANT = 'italian_restaurant',
    JAPANESE_RESTAURANT = 'japanese_restaurant',
    KOREAN_RESTAURANT = 'korean_restaurant',
    LEBANESE_RESTAURANT = 'lebanese_restaurant',
    MEAL_DELIVERY = 'meal_delivery',
    MEAL_TAKEAWAY = 'meal_takeaway',
    MEDITERRANEAN_RESTAURANT = 'mediterranean_restaurant',
    MEXICAN_RESTAURANT = 'mexican_restaurant',
    MIDDLE_EASTERN_RESTAURANT = 'middle_eastern_restaurant',
    PIZZA_RESTAURANT = 'pizza_restaurant',
    RAMEN_RESTAURANT = 'ramen_restaurant',
    RESTAURANT = 'restaurant',
    SANDWICH_SHOP = 'sandwich_shop',
    SEAFOOD_RESTAURANT = 'seafood_restaurant',
    SPANISH_RESTAURANT = 'spanish_restaurant',
    STEAK_HOUSE = 'steak_house',
    SUSHI_RESTAURANT = 'sushi_restaurant',
    THAI_RESTAURANT = 'thai_restaurant',
    TURKISH_RESTAURANT = 'turkish_restaurant',
    VEGAN_RESTAURANT = 'vegan_restaurant',
    VEGETARIAN_RESTAURANT = 'vegetarian_restaurant',
    VIETNAMESE_RESTAURANT = 'vietnamese_restaurant',
}

export const cuisineMapping: { [key in RestaurantType]: string } = {
    [RestaurantType.DESSERT]: "dessert",
    [RestaurantType.AMERICAN_RESTAURANT]: "american",
    [RestaurantType.BAKERY]: "bakery",
    [RestaurantType.BAR]: "bar",
    [RestaurantType.BARBECUE_RESTAURANT]: "barbecue",
    [RestaurantType.BRAZILIAN_RESTAURANT]: "brazilian",
    [RestaurantType.BREAKFAST_RESTAURANT]: "breakfast",
    [RestaurantType.BRUNCH_RESTAURANT]: "brunch",
    [RestaurantType.CAFE]: "cafe",
    [RestaurantType.CHINESE_RESTAURANT]: "chinese",
    [RestaurantType.COFFEE_SHOP]: "coffee shop",
    [RestaurantType.FAST_FOOD_RESTAURANT]: "fast food",
    [RestaurantType.FRENCH_RESTAURANT]: "french",
    [RestaurantType.GREEK_RESTAURANT]: "greek",
    [RestaurantType.HAMBURGER_RESTAURANT]: "hamburger",
    [RestaurantType.ICE_CREAM_SHOP]: "ice cream",
    [RestaurantType.INDIAN_RESTAURANT]: "indian",
    [RestaurantType.INDONESIAN_RESTAURANT]: "indonesian",
    [RestaurantType.ITALIAN_RESTAURANT]: "italian",
    [RestaurantType.JAPANESE_RESTAURANT]: "japanese",
    [RestaurantType.KOREAN_RESTAURANT]: "korean",
    [RestaurantType.LEBANESE_RESTAURANT]: "lebanese",
    [RestaurantType.MEAL_DELIVERY]: "meal delivery",
    [RestaurantType.MEAL_TAKEAWAY]: "meal takeaway",
    [RestaurantType.MEDITERRANEAN_RESTAURANT]: "mediterranean",
    [RestaurantType.MEXICAN_RESTAURANT]: "mexican",
    [RestaurantType.MIDDLE_EASTERN_RESTAURANT]: "middle eastern",
    [RestaurantType.PIZZA_RESTAURANT]: "pizza",
    [RestaurantType.RAMEN_RESTAURANT]: "ramen",
    [RestaurantType.RESTAURANT]: "restaurant",
    [RestaurantType.SANDWICH_SHOP]: "sandwich",
    [RestaurantType.SEAFOOD_RESTAURANT]: "seafood",
    [RestaurantType.SPANISH_RESTAURANT]: "spanish",
    [RestaurantType.STEAK_HOUSE]: "steak house",
    [RestaurantType.SUSHI_RESTAURANT]: "sushi",
    [RestaurantType.THAI_RESTAURANT]: "thai",
    [RestaurantType.TURKISH_RESTAURANT]: "turkish",
    [RestaurantType.VEGAN_RESTAURANT]: "vegan",
    [RestaurantType.VEGETARIAN_RESTAURANT]: "vegetarian",
    [RestaurantType.VIETNAMESE_RESTAURANT]: "vietnamese",
};